"""Interactive setup wizard for StreamFLACr.

Detects existing SoundCloud login and Soulseek installation,
prompts for anything missing, writes .env, installs serato-tools,
and registers the launchd daemon.
"""

import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from .config import CONFIG_DIR, DOWNLOAD_DIR, SERATO_DIR

logger = logging.getLogger(__name__)

ENV_FILE = CONFIG_DIR / ".env"
INSTALLED_PLIST = Path.home() / "Library" / "LaunchAgents" / "com.djtchill.streamflacr.plist"


def _get_package_python() -> str:
    return sys.executable


# ── Serato tools installation ─────────────────────────────────────────

def install_serato_tools() -> bool:
    """Install serato-tools with --no-deps into the current environment."""
    print("  Installing serato-tools (Serato crate support)...")
    python = _get_package_python()

    result = subprocess.run(
        ["uv", "pip", "install", "--python", python, "serato-tools", "--no-deps"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print("  ✓ serato-tools installed")
        return True

    result = subprocess.run(
        [python, "-m", "pip", "install", "serato-tools", "--no-deps"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print("  ✓ serato-tools installed")
        return True

    print("  Warning: could not install serato-tools. Smart crate creation will be skipped.")
    print(f"  Install manually: {python} -m pip install serato-tools --no-deps")
    return False


def check_serato_tools() -> bool:
    try:
        import serato_tools  # noqa: F401
        return True
    except ImportError:
        return False


# ── SoundCloud detection ──────────────────────────────────────────────

def detect_soundcloud_login() -> bool:
    """Check if the user is logged into SoundCloud in Chrome."""
    from .soundcloud import has_oauth
    return has_oauth()


def extract_soundcloud_user_url() -> str | None:
    """Extract the user's SoundCloud profile URL from the API.

    Requires OAuth token from Chrome cookies.
    """
    from .soundcloud import _api_get
    try:
        me = _api_get("me")
        if me:
            return me.get("permalink_url")
    except Exception as e:
        logger.debug("Could not get SoundCloud user URL: %s", e)
    return None


def prompt_soundcloud_login() -> None:
    print("\n  SoundCloud login not detected in Chrome.")
    print("  Opening SoundCloud login page in your browser...")
    print("  Please log in, then come back and press Enter.\n")
    subprocess.run(["open", "https://soundcloud.com/signin"], check=False)
    input("  Press Enter once you've logged into SoundCloud in Chrome... ")


# ── Soulseek detection ────────────────────────────────────────────────

def detect_soulseek_installation() -> bool:
    for path in [
        Path("/Applications/SoulseekQt.app"),
        Path.home() / "Applications" / "SoulseekQt.app",
    ]:
        if path.exists():
            return True
    return False


def detect_soulseek_data() -> bool:
    data_dir = Path.home() / ".SoulseekQt"
    return data_dir.exists() and any(data_dir.iterdir())


def prompt_soulseek_setup() -> dict:
    print("\n  Soulseek credentials required for downloading FLAC files.")
    print("  If you don't have an account, visit https://www.slsknet.org\n")
    username = ""
    while not username:
        username = input("  Soulseek username: ").strip()
    password = ""
    while not password:
        password = input("  Soulseek password: ").strip()
    return {"username": username, "password": password}


# ── .env file ──────────────────────────────────────────────────────────

def write_env_file(slsk_creds: dict, user_url: str, poll_interval: int = 300) -> None:
    content = f"""\
# StreamFLACr configuration
# Generated by setup wizard

# Soulseek credentials
SLSK_USERNAME={slsk_creds['username']}
SLSK_PASSWORD={slsk_creds['password']}

# SoundCloud user URL (all playlists will be monitored automatically)
SOUNDCLOUD_USER_URL={user_url}

# Poll interval in seconds
SOUNDCLOUD_POLL_INTERVAL={poll_interval}

# Download directory (Serato Auto Import watches this folder)
DOWNLOAD_DIR={DOWNLOAD_DIR}

# Serato database directory
SERATO_DIR={SERATO_DIR}

# Search preferences
SEARCH_TIMEOUT=30
PREFER_FREE_SLOTS=1
MIN_FILESIZE_MB=5
"""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(content)
    print(f"\n  Config written to {ENV_FILE}")


# ── LaunchDaemon ───────────────────────────────────────────────────────

def _generate_plist() -> str:
    """Generate LaunchDaemon plist content dynamically."""
    import shutil
    streamflacr_path = shutil.which("streamflacr") or "streamflacr"
    log_dir = Path.home() / "Library" / "Logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.djtchill.streamflacr</string>
    <key>ProgramArguments</key>
    <array>
        <string>{streamflacr_path}</string>
        <string>--daemon</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{Path.home()}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>{Path(streamflacr_path).parent}:/usr/local/bin:/usr/bin:/bin</string>
        <key>STREAMFLACR_CONFIG_DIR</key>
        <string>{CONFIG_DIR}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{log_dir / "streamflacr.log"}</string>
    <key>StandardErrorPath</key>
    <string>{log_dir / "streamflacr.err"}</string>
</dict>
</plist>"""


def register_launchdaemon() -> bool:
    plist_content = _generate_plist()
    subprocess.run(
        ["launchctl", "unload", str(INSTALLED_PLIST)],
        capture_output=True, check=False,
    )
    INSTALLED_PLIST.write_text(plist_content)
    result = subprocess.run(
        ["launchctl", "load", str(INSTALLED_PLIST)],
        capture_output=True, text=True, check=False,
    )
    if result.returncode == 0:
        print(f"  ✓ LaunchDaemon registered: {INSTALLED_PLIST.name}")
        print("  StreamFLACr will start automatically on login.")
        return True
    print(f"  Warning: could not load LaunchDaemon: {result.stderr.strip()}")
    return False


def unregister_launchdaemon() -> bool:
    subprocess.run(
        ["launchctl", "unload", str(INSTALLED_PLIST)],
        capture_output=True, check=False,
    )
    if INSTALLED_PLIST.exists():
        INSTALLED_PLIST.unlink()
        print("  LaunchDaemon removed.")
        return True
    return False


# ── Main wizard ────────────────────────────────────────────────────────

def run_setup() -> None:
    print()
    print("  ───────────────────────────────────────────")
    print("   StreamFLACr Setup Wizard")
    print("  ───────────────────────────────────────────")
    print()

    # ── Step 1: SoundCloud ──
    print("  [1/4] Checking SoundCloud login...")
    sc_logged_in = detect_soundcloud_login()
    user_url = None
    if sc_logged_in:
        print("  ✓ SoundCloud login detected in Chrome")
        user_url = extract_soundcloud_user_url()
        if user_url:
            print(f"  ✓ User profile: {user_url}")
        else:
            print("  Could not auto-detect profile URL (token may need refreshing)")
    else:
        print("  ✗ SoundCloud login not found in Chrome")
        prompt_soundcloud_login()
        if detect_soundcloud_login():
            user_url = extract_soundcloud_user_url()
            if user_url:
                print(f"  ✓ User profile: {user_url}")

    if not user_url:
        print("\n  Could not auto-detect your SoundCloud profile URL.")
        print("  Find it at: https://soundcloud.com/ (click your avatar > Profile)\n")
        user_url = ""
        while not user_url:
            user_url = input("  SoundCloud profile URL: ").strip()

    # ── Step 2: Soulseek ──
    print("\n  [2/4] Checking Soulseek...")
    slsk_installed = detect_soulseek_installation()
    slsk_has_data = detect_soulseek_data()
    if slsk_installed:
        print("  ✓ SoulseekQt.app found")
    else:
        print("  ✗ SoulseekQt.app not found in Applications folder")
        print("  SoulseekQt is recommended but not required (the built-in client works too).")
        answer = input("  Install SoulseekQt? [y/N]: ").strip().lower()
        if answer == "y":
            subprocess.run(["open", "https://www.slsknet.org/download"], check=False)
            input("  Press Enter once SoulseekQt is installed... ")
    if slsk_has_data:
        print("  ✓ SoulseekQt data found (you've logged in before)")
    else:
        print("  Note: No SoulseekQt login data found.")
    slsk_creds = prompt_soulseek_setup()

    # ── Step 3: Serato integration ──
    print("\n  [3/4] Serato integration...")
    has_serato = check_serato_tools()
    if has_serato:
        print("  ✓ serato-tools already installed")
    else:
        install_serato_tools()

    # ── Step 4: Write config + register daemon ──
    print("\n  [4/4] Finishing up...")
    write_env_file(slsk_creds, user_url)
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    print(f"  ✓ Download directory: {DOWNLOAD_DIR}")
    print(f"  ✓ All playlists will be monitored automatically")

    print()
    answer = input("  Start StreamFLACr automatically on login? [Y/n]: ").strip().lower()
    if answer in ("", "y", "yes"):
        register_launchdaemon()
    else:
        print("  Skipping daemon registration. Run `streamflacr --daemon` to start manually.")

    print()
    print("  ───────────────────────────────────────────")
    print("  Setup complete!")
    print()
    print("  All your SoundCloud playlists are now being monitored.")
    print("  New tracks will be auto-downloaded as FLAC and tagged with")
    print("  the playlist name as the Label field for Serato smart crates.")
    print()
    print("  Run now:       streamflacr")
    print("  Run as daemon:  streamflacr --daemon")
    print("  Re-run setup:   streamflacr setup")
    print("  ───────────────────────────────────────────")
    print()
