"""Interactive setup wizard for StreamFLACr.

Detects existing SoundCloud login and Soulseek installation,
prompts for anything missing, writes .env,
and registers the launchd daemon.
"""

import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from .config import CONFIG_DIR, DOWNLOAD_DIR, SERATO_DIR, STAGING_DIR

logger = logging.getLogger(__name__)

ENV_FILE = CONFIG_DIR / ".env"
INSTALLED_PLIST = Path.home() / "Library" / "LaunchAgents" / "com.streamflacr.plist"
# Legacy plist name from v0.12.0 and earlier — must be cleaned up on upgrade
LEGACY_PLIST = Path.home() / "Library" / "LaunchAgents" / "com.djtchill.streamflacr.plist"


def kill_running_daemon() -> bool:
    """Kill any stale streamflacr daemon from a previous run.

    Unloads the LaunchAgent first (to prevent launchd from respawning it),
    then kills any remaining Python processes.
    """
    import signal
    # Unload LaunchAgents so launchd doesn't respawn the daemon
    for plist in (INSTALLED_PLIST, LEGACY_PLIST):
        if plist.exists():
            subprocess.run(
                ["launchctl", "unload", str(plist)],
                capture_output=True, check=False,
            )

    my_pid = os.getpid()
    parent_pid = os.getppid()
    killed = False
    try:
        result = subprocess.run(
            ["pgrep", "-f", "python.*streamflacr"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            for pid_str in result.stdout.strip().split("\n"):
                try:
                    pid = int(pid_str.strip())
                    if pid in (my_pid, parent_pid):
                        continue
                    os.kill(pid, signal.SIGTERM)
                    killed = True
                except (ValueError, ProcessLookupError, PermissionError):
                    pass
    except Exception:
        pass
    if killed:
        import time
        time.sleep(1)
    return killed


# ── Serato tools installation ─────────────────────────────────────────

# ── SoundCloud detection ──────────────────────────────────────────────

def detect_soundcloud_login() -> bool:
    """Check if the user is logged into SoundCloud in Chrome."""
    from .soundcloud import has_oauth
    return has_oauth()


def extract_soundcloud_user_url() -> str | None:
    """Extract the user's SoundCloud profile URL from the API.

    Requires OAuth token from Chrome cookies.
    """
    from .soundcloud import _api_get
    try:
        me = _api_get("me")
        if me:
            return me.get("permalink_url")
    except Exception as e:
        logger.debug("Could not get SoundCloud user URL: %s", e)
    return None


def prompt_soundcloud_login() -> None:
    print("\n  SoundCloud login not detected in Chrome.")
    print("  Opening SoundCloud login page in your browser...")
    print("  Please log in, then come back and press Enter.\n")
    subprocess.run(["open", "https://soundcloud.com/signin"], check=False)
    input("  Press Enter once you've logged into SoundCloud in Chrome... ")


# ── Soulseek detection ────────────────────────────────────────────────

def detect_soulseek_installation() -> bool:
    for path in [
        Path("/Applications/SoulseekQt.app"),
        Path.home() / "Applications" / "SoulseekQt.app",
    ]:
        if path.exists():
            return True
    return False


def detect_soulseek_data() -> bool:
    data_dir = Path.home() / ".SoulseekQt"
    return data_dir.exists() and any(data_dir.iterdir())


def prompt_soulseek_setup() -> dict:
    print("\n  Soulseek credentials required for downloading FLAC files.")
    print("  If you don't have an account, visit https://www.slsknet.org\n")
    username = ""
    while not username:
        username = input("  Soulseek username: ").strip()
    password = ""
    while not password:
        password = input("  Soulseek password: ").strip()
    return {"username": username, "password": password}


# ── .env file ──────────────────────────────────────────────────────────

def write_env_file(slsk_creds: dict, user_url: str, poll_interval: int = 300) -> None:
    content = f"""\
# StreamFLACr configuration
# Generated by setup wizard

# Soulseek credentials
SLSK_USERNAME={slsk_creds['username']}
SLSK_PASSWORD={slsk_creds['password']}

# SoundCloud user URL (all playlists will be monitored automatically)
SOUNDCLOUD_USER_URL={user_url}

# Poll interval in seconds
SOUNDCLOUD_POLL_INTERVAL={poll_interval}

# Download directory (Serato Auto Import watches this folder)
DOWNLOAD_DIR={DOWNLOAD_DIR}

# Staging directory (files are tagged here before importing)
STAGING_DIR={STAGING_DIR}
SERATO_DIR={SERATO_DIR}

# Search preferences
SEARCH_TIMEOUT=30
PREFER_FREE_SLOTS=1
MIN_FILESIZE_MB=5
"""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(content)
    print(f"\n  Config written to {ENV_FILE}")


# ── LaunchDaemon ───────────────────────────────────────────────────────

def _generate_plist() -> str:
    """Generate LaunchDaemon plist content dynamically."""
    import shutil
    streamflacr_path = shutil.which("streamflacr") or "streamflacr"
    log_dir = Path.home() / "Library" / "Logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.streamflacr</string>
    <key>ProgramArguments</key>
    <array>
        <string>{streamflacr_path}</string>
        <string>--daemon</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{Path.home()}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>{Path(streamflacr_path).parent}:/usr/local/bin:/usr/bin:/bin</string>
        <key>STREAMFLACR_CONFIG_DIR</key>
        <string>{CONFIG_DIR}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{log_dir / "streamflacr.log"}</string>
    <key>StandardErrorPath</key>
    <string>{log_dir / "streamflacr.err"}</string>
</dict>
</plist>"""


def register_launchdaemon() -> bool:
    kill_running_daemon()
    # Clean up legacy plist from v0.12.0 and earlier
    if LEGACY_PLIST.exists():
        subprocess.run(
            ["launchctl", "unload", str(LEGACY_PLIST)],
            capture_output=True, check=False,
        )
        LEGACY_PLIST.unlink()
    plist_content = _generate_plist()
    subprocess.run(
        ["launchctl", "unload", str(INSTALLED_PLIST)],
        capture_output=True, check=False,
    )
    INSTALLED_PLIST.write_text(plist_content)
    result = subprocess.run(
        ["launchctl", "load", str(INSTALLED_PLIST)],
        capture_output=True, text=True, check=False,
    )
    if result.returncode == 0:
        print(f"  ✓ LaunchDaemon registered: {INSTALLED_PLIST.name}")
        print("  StreamFLACr will start automatically on login.")
        return True
    print(f"  Warning: could not load LaunchDaemon: {result.stderr.strip()}")
    return False


def unregister_launchdaemon() -> bool:
    """Stop and remove the LaunchDaemon. Does NOT touch Serato data."""
    kill_running_daemon()
    subprocess.run(
        ["launchctl", "unload", str(INSTALLED_PLIST)],
        capture_output=True, check=False,
    )
    if INSTALLED_PLIST.exists():
        INSTALLED_PLIST.unlink()
        print("  LaunchDaemon removed.")
        return True
    return False


def full_uninstall() -> None:
    """Remove all StreamFLACr artifacts except Serato data.

    Serato crates and the _Serato_ directory are never modified during
    uninstall — that data is too sensitive. Smart crates created by
    StreamFLACr remain in place for the user to manage manually.

    The user is prompted about whether to keep downloaded music files
    (the staging data in the config directory). Everything else is removed.
    """
    print()
    print("  Uninstalling StreamFLACr...")
    print()

    # 1. Stop the daemon
    if kill_running_daemon():
        print("  ✓ Stopped running daemon")
    else:
        print("  - No daemon running")

    # 2. Unload and remove LaunchAgents (current + legacy)
    for plist_path, label in [(INSTALLED_PLIST, "current"), (LEGACY_PLIST, "legacy")]:
        subprocess.run(
            ["launchctl", "unload", str(plist_path)],
            capture_output=True, check=False,
        )
        if plist_path.exists():
            plist_path.unlink()
            print(f"  ✓ Removed {label} LaunchAgent plist")
        else:
            print(f"  - No {label} LaunchAgent found")

    # 3. Ask about downloaded music files before removing config
    keep_downloads = False
    if CONFIG_DIR.exists():
        staging = CONFIG_DIR / "staging"
        state = CONFIG_DIR / "state.json"
        has_downloads = (staging.exists() and any(staging.iterdir())) or state.exists()
        if has_downloads:
            answer = input(
                "\n  Keep downloaded music files and migration data? [Y/n]: "
            ).strip().lower()
            keep_downloads = answer in ("", "y", "yes")

        if keep_downloads:
            # Preserve staging dir and state.json, remove everything else
            for item in CONFIG_DIR.iterdir():
                if item.name in ("staging", "state.json"):
                    continue
                if item.is_dir():
                    shutil.rmtree(item)
                else:
                    item.unlink()
            print(f"  ✓ Removed config (kept staging & state)")
        else:
            shutil.rmtree(CONFIG_DIR)
            print(f"  ✓ Removed config: {CONFIG_DIR}")
    else:
        print("  - No config directory found")

    # 4. Remove log files
    removed_logs = 0
    for log in Path.home().glob("Library/Logs/streamflacr*"):
        log.unlink()
        removed_logs += 1
    if removed_logs:
        print(f"  ✓ Removed {removed_logs} log file(s)")
    else:
        print("  - No log files found")

    # 5. Remove the uv/pipx tool installation
    uninstalled_tool = False
    result = subprocess.run(
        ["uv", "tool", "uninstall", "streamflacr"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print("  ✓ Uninstalled uv tool")
        uninstalled_tool = True
    else:
        # Try pipx
        result2 = subprocess.run(
            ["pipx", "uninstall", "streamflacr"],
            capture_output=True, text=True,
        )
        if result2.returncode == 0:
            print("  ✓ Uninstalled pipx tool")
            uninstalled_tool = True
    if not uninstalled_tool:
        print("  - Could not auto-uninstall the tool; run manually:")
        print("    uv tool uninstall streamflacr")

    print()
    print("  ───────────────────────────────────────────")
    print("  StreamFLACr has been fully uninstalled.")
    print()
    from .serato_crate import BACKUP_DIR
    print("  The following were NOT removed (Serato data is sensitive):")
    print(f"    Smart crates: {SERATO_DIR / 'SmartCrates'}")
    print(f"    Downloaded files: {DOWNLOAD_DIR}")
    print(f"    Serato backups: {BACKUP_DIR}")
    if keep_downloads:
        print(f"    Migration data: {CONFIG_DIR}")
    print("  ───────────────────────────────────────────")
    print()


# ── Main wizard ────────────────────────────────────────────────────────

def run_setup(*, non_interactive: bool = False) -> None:
    print()
    print("  ───────────────────────────────────────────")
    print("   StreamFLACr Setup Wizard")
    print("  ───────────────────────────────────────────")
    print()

    # ── Step 1: SoundCloud ──
    print("  [1/3] Checking SoundCloud login...")
    sc_logged_in = detect_soundcloud_login()
    user_url = None
    if sc_logged_in:
        print("  ✓ SoundCloud login detected in Chrome")
        user_url = extract_soundcloud_user_url()
        if user_url:
            print(f"  ✓ User profile: {user_url}")
        else:
            print("  Could not auto-detect profile URL (token may need refreshing)")
    else:
        print("  ✗ SoundCloud login not found in Chrome")
        if non_interactive:
            print("  Non-interactive mode: opening SoundCloud login page")
            print("  Please log in, then re-run `streamflacr setup`.")
            subprocess.run(["open", "https://soundcloud.com/signin"], check=False)
            sys.exit(1)
        prompt_soundcloud_login()
        if detect_soundcloud_login():
            user_url = extract_soundcloud_user_url()
            if user_url:
                print(f"  ✓ User profile: {user_url}")

    if not user_url:
        if non_interactive:
            print("  ERROR: Could not detect SoundCloud profile. Set SOUNDCLOUD_USER_URL in .env.")
            sys.exit(1)
        print("\n  Could not auto-detect your SoundCloud profile URL.")
        print("  Find it at: https://soundcloud.com/ (click your avatar > Profile)\n")
        user_url = ""
        while not user_url:
            user_url = input("  SoundCloud profile URL: ").strip()

    # ── Step 2: Soulseek ──
    print("\n  [2/3] Checking Soulseek...")
    slsk_installed = detect_soulseek_installation()
    slsk_has_data = detect_soulseek_data()
    if slsk_installed:
        print("  ✓ SoulseekQt.app found")
    else:
        print("  ✗ SoulseekQt.app not found in Applications folder")
        print("  SoulseekQt is recommended but not required (the built-in client works too).")
        if not non_interactive:
            answer = input("  Install SoulseekQt? [y/N]: ").strip().lower()
            if answer == "y":
                subprocess.run(["open", "https://www.slsknet.org/download"], check=False)
                input("  Press Enter once SoulseekQt is installed... ")
    if slsk_has_data:
        print("  ✓ SoulseekQt data found (you've logged in before)")
    else:
        print("  Note: No SoulseekQt login data found.")
    if non_interactive:
        slsk_username = os.environ.get("SLSK_USERNAME", "")
        slsk_password = os.environ.get("SLSK_PASSWORD", "")
        if not slsk_username or not slsk_password:
            print("  ERROR: Non-interactive mode requires SLSK_USERNAME and SLSK_PASSWORD env vars.")
            sys.exit(1)
        slsk_creds = {"username": slsk_username, "password": slsk_password}
    else:
        slsk_creds = prompt_soulseek_setup()

    # ── Step 3: Write config + register daemon ──
    print("\n  [3/3] Finishing up...")
    write_env_file(slsk_creds, user_url)
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    print(f"  ✓ Download directory: {DOWNLOAD_DIR}")
    print(f"  ✓ All playlists will be monitored automatically")

    print()
    if non_interactive:
        register_launchdaemon()
    else:
        answer = input("  Start StreamFLACr automatically on login? [Y/n]: ").strip().lower()
        if answer in ("", "y", "yes"):
            register_launchdaemon()
        else:
            print("  Skipping daemon registration. Run `streamflacr --daemon` to start manually.")

    print()
    print("  ───────────────────────────────────────────")
    print("  Setup complete!")
    print()
    print("  All your SoundCloud playlists are now being monitored.")
    print("  New tracks will be auto-downloaded as FLAC and tagged with")
    print("  the playlist name as the Comment field for Serato smart crates.")
    print()
    print("  Run now:       streamflacr")
    print("  Run as daemon:  streamflacr --daemon")
    print("  Re-run setup:   streamflacr setup")
    print("  ───────────────────────────────────────────")
    print()
